version: "3"

services:
  marketplace:
    container_name: tai-test
    image: tai:latest
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    networks:
      - mongo_network

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: your_root_username
      MONGO_INITDB_ROOT_PASSWORD: your_root_password
    networks:
      - mongo_network

volumes:
  mongodb_data:

networks:
  mongo_network:
